DROP TABLE IF EXISTS person;

CREATE TABLE person (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  birth_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_person PRIMARY KEY (id)
);

DROP TABLE IF EXISTS passport;


CREATE TABLE passport (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  serial_number INTEGER,
  number INTEGER NOT NULL,
  issue_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  expiration_date date NOT NULL,
  active BOOLEAN NOT NULL,
  passport_type INTEGER NOT NULL,
  person_id BIGINT,
  CONSTRAINT pk_passport PRIMARY KEY (id)
);

ALTER TABLE passport ADD CONSTRAINT uc_passport_number UNIQUE (number);

ALTER TABLE passport ADD CONSTRAINT FK_PASSPORT_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (1,'George ','Washington','2011-08-03 14:12:46');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (2,'John ','Adams','2008-07-31 21:17:36');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (3,'Thomas ','Jefferson','1985-08-02 17:46:30');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (4,'James ','Madison','1997-11-24 19:11:13');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (5,'James ','Monroe','1972-12-31 18:07:34');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (6,'John Quincy ','Adams','1992-08-15 16:39:12');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (7,'Andrew ','Jackson','2021-11-04 14:36:50');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (8,'Martin ','Van Buren','2006-05-24 16:07:42');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (9,'William Henry ','Harrison','1993-06-03 19:21:54');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (10,'John ','Tyler','2001-11-13 17:52:30');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (11,'James K. ','Polk','2000-06-21 1:26:29');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (12,'Zachary ','Taylor','1976-01-18 14:43:12');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (13,'Millard ','Fillmore','2008-01-09 19:52:18');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (14,'Franklin ','Pierce','1977-04-19 14:03:35');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (15,'James ','Buchanan','1987-10-07 22:19:34');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (16,'Abraham ','Lincoln','2011-02-24 22:35:03');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (17,'Andrew ','Johnson','1986-05-22 1:29:25');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (18,'Ulysses S. ','S. Grant','1992-06-20 17:37:19');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (19,'Rutherford Birchard ','Hayes','1998-11-29 14:39:24');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (20,'James A. ','Garfield','1994-08-11 20:32:04');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (21,'Chester A. ','Arthur','1977-10-15 1:04:11');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (22,'Grover ','Cleveland','1991-08-19 19:00:27');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (23,'Benjamin ','Harrison','1994-03-14 19:19:34');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (24,'Grover ','Cleveland','2010-04-13 23:00:29');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (25,'William ','McKinley','1988-06-27 14:32:21');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (26,'Theodore ','Roosevelt','1994-04-16 1:19:17');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (27,'William H. ','Taft','1994-02-05 13:42:51');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (28,'Woodrow ','Wilson','1981-06-29 15:19:53');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (29,'Warren G. ','Harding','1973-05-24 21:07:38');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (30,'Calvin ','Coolidge','2006-04-07 0:53:56');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (31,'Herbert ','Hoover','1987-09-19 22:43:54');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (32,'Franklin D. ','Roosevelt','1988-09-29 14:46:37');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (33,'Harry S. ','Truman','1978-09-22 14:24:28');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (34,'Dwight D. ','Eisenhower','1976-04-17 0:01:24');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (35,'John F. ','Kennedy','2000-12-19 19:00:17');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (36,'Lyndon B. ','Johnson','1987-07-08 1:36:55');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (37,'Richard M. ','Nixon','2017-07-21 15:04:58');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (38,'Gerald R. ','Ford','2002-04-12 14:09:45');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (39,'Jimmy ','Carter','1990-07-15 14:39:55');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (40,'Ronald ','Reagan','1975-12-14 22:01:01');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (41,'George ','Bush','1993-05-01 14:36:02');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (42,'Bill ','Clinton','2019-06-01 12:18:19');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (43,'George W. ','Bush','1970-01-27 13:07:43');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (44,'Barack ','Obama','1998-08-08 0:54:29');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (45,'Donald J. ','Trump','1999-06-21 14:36:14');
INSERT INTO public.person (id, first_name, last_name, birth_date) VALUES (46,'Joseph R. ','Biden','1987-08-17 13:29:51');

INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (1,8266,196823,'1977-05-03 0:22:23','1987-05-03 20:29:19',true,1,18);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (2,7830,342889,'1986-03-25 17:05:06','1996-03-25 0:48:17',false,1,11);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (3,3720,932659,'1989-03-12 19:27:28','1999-03-12 23:23:47',false,1,14);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (4,5399,550553,'2006-04-10 23:34:37','2016-04-10 0:31:48',true,1,16);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (5,9514,495865,'1981-03-30 22:07:06','1991-03-30 15:38:01',false,0,34);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (6,3112,889303,'1974-02-28 23:18:19','1984-02-28 14:03:19',false,0,21);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (7,5706,613359,'2006-05-31 20:03:58','2016-05-31 15:03:25',false,0,30);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (8,7821,151726,'2006-05-08 21:23:39','2016-05-08 19:05:57',true,0,38);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (9,2461,828139,'1989-01-07 20:38:51','1999-01-07 18:32:37',false,0,24);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (10,7031,242866,'2004-03-29 14:03:45','2014-03-29 16:33:16',true,0,14);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (11,3910,486731,'1980-07-27 13:08:25','1990-07-27 13:34:45',false,0,14);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (12,6188,578185,'2008-05-29 23:48:09','2018-05-29 22:55:26',false,1,27);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (13,7627,989749,'1970-10-19 16:24:18','1980-10-19 20:05:30',true,1,26);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (14,3220,874714,'2019-09-24 18:04:17','2029-09-24 18:08:43',false,1,20);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (15,1169,703639,'1993-10-06 19:33:50','2003-10-06 0:16:35',false,1,17);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (16,1382,583727,'1972-03-19 22:13:59','1982-03-19 14:47:16',true,1,17);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (17,5375,666705,'1999-02-26 19:34:58','2009-02-26 15:16:14',true,0,13);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (18,1981,504443,'1986-09-09 15:44:49','1996-09-09 0:16:20',false,0,5);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (19,9114,379273,'2004-01-09 16:59:25','2014-01-09 21:11:06',true,0,28);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (20,6477,736724,'2001-01-09 0:53:48','2011-01-09 0:22:14',true,1,6);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (21,1632,989175,'1980-05-25 18:02:46','1990-05-25 13:22:09',false,0,29);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (22,4502,636372,'2006-12-29 15:30:54','2016-12-29 0:30:13',false,1,16);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (23,5074,114593,'1995-09-30 20:57:47','2005-09-30 23:32:57',false,1,2);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (24,9303,499025,'2010-10-02 17:50:50','2020-10-02 17:41:46',false,1,15);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (25,5358,588710,'1983-10-19 17:43:17','1993-10-19 23:02:02',false,1,37);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (26,2795,716885,'1992-02-15 16:42:57','2002-02-15 1:42:15',false,1,10);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (27,5922,770657,'1997-09-30 12:13:25','2007-09-30 22:20:01',true,1,6);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (28,6079,296137,'1972-08-17 18:44:17','1982-08-17 20:06:21',true,1,8);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (29,3679,849118,'1973-11-07 23:49:16','1983-11-07 23:06:07',true,0,27);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (30,4183,859746,'2018-08-20 13:41:54','2028-08-20 19:33:52',true,0,18);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (31,4449,500998,'1978-10-06 23:19:01','1988-10-06 13:30:36',false,1,40);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (32,1140,213736,'1971-06-22 17:21:56','1981-06-22 23:33:49',true,0,26);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (33,2149,804708,'2017-10-22 23:56:14','2027-10-22 23:18:46',false,0,21);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (34,6834,893207,'2005-11-18 16:38:03','2015-11-18 14:41:14',false,0,26);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (35,6588,930679,'2015-04-18 14:29:39','2025-04-18 13:36:32',true,0,7);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (36,1026,527220,'2017-03-04 22:29:49','2027-03-04 12:44:08',true,1,24);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (37,5808,316383,'1980-12-20 13:02:16','1990-12-20 20:14:49',false,0,5);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (38,2420,992318,'1982-04-14 14:59:58','1992-04-14 0:16:06',false,0,30);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (39,1831,492934,'2003-02-06 21:49:40','2013-02-06 22:30:09',true,0,21);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (40,3424,584885,'2019-11-07 0:32:43','2029-11-07 17:25:59',false,1,10);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (41,8513,903910,'2001-05-21 16:50:17','2011-05-21 17:34:46',false,1,17);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (42,8057,885900,'1990-09-19 20:16:35','2000-09-19 0:25:31',true,1,21);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (43,9862,252912,'1977-08-06 14:48:44','1987-08-06 16:13:53',false,0,36);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (44,7747,915426,'1981-09-12 16:26:06','1991-09-12 20:31:38',true,1,39);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (45,9136,893461,'2016-07-30 16:14:10','2026-07-30 16:36:14',true,1,10);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (46,5953,829392,'1981-06-26 15:31:26','1991-06-26 15:37:18',false,0,19);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (47,8867,367189,'2020-05-29 23:42:16','2030-05-29 0:59:59',false,1,6);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (48,7445,523615,'1983-09-04 23:36:13','1993-09-04 21:46:00',false,0,25);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (49,7108,408944,'1975-03-29 20:26:47','1985-03-29 18:39:36',true,0,6);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (50,6061,568297,'1970-10-15 19:30:34','1980-10-15 18:46:07',false,1,8);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (51,4364,200443,'1970-08-16 14:36:07','1980-08-16 13:41:42',true,0,43);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (52,4519,249047,'1998-04-19 20:28:51','2008-04-19 15:57:47',true,1,37);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (53,7674,904339,'1989-04-02 19:18:24','1999-04-02 17:40:59',true,0,4);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (54,1175,447396,'1981-11-16 22:34:03','1991-11-16 21:43:44',true,0,41);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (55,7917,202263,'1984-06-04 19:43:44','1994-06-04 21:12:57',true,0,20);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (56,1686,384873,'2002-05-31 23:34:16','2012-05-31 17:33:13',false,0,12);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (57,2300,105145,'1985-05-08 23:45:54','1995-05-08 21:35:32',true,1,12);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (58,6585,700192,'1976-01-21 15:29:46','1986-01-21 22:31:52',false,1,1);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (59,8481,193929,'2012-06-29 23:06:31','2022-06-29 0:50:55',false,0,44);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (60,5140,901119,'1997-04-03 14:55:34','2007-04-03 21:07:32',false,0,36);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (61,2228,884868,'2001-11-24 0:38:29','2011-11-24 14:50:11',true,0,31);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (62,4084,604107,'1977-11-28 15:11:23','1987-11-28 23:43:06',true,1,11);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (63,7553,659367,'1993-03-05 22:20:47','2003-03-05 20:31:57',false,0,17);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (64,6897,899210,'2019-10-13 18:23:58','2029-10-13 17:15:10',true,1,20);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (65,7529,705499,'2001-03-13 20:41:24','2011-03-13 23:17:02',false,0,44);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (66,2532,846087,'1992-03-03 17:21:46','2002-03-03 16:44:09',false,0,16);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (67,3686,119842,'1998-10-28 16:08:45','2008-10-28 1:06:15',false,1,39);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (68,9999,951113,'2005-01-27 21:44:51','2015-01-27 17:51:21',false,1,3);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (69,9469,967992,'2009-09-27 0:24:16','2019-09-27 13:19:08',false,1,21);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (70,2803,452800,'2004-01-02 15:19:22','2014-01-02 19:27:12',true,1,9);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (71,4349,263567,'1992-01-23 20:06:28','2002-01-23 23:20:44',false,0,14);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (72,3229,309630,'1988-10-26 22:56:46','1998-10-26 19:50:33',true,1,12);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (73,6699,378798,'2011-04-06 20:53:11','2021-04-06 20:51:05',false,1,10);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (74,1660,384364,'1984-01-01 18:39:40','1994-01-01 21:41:56',true,0,40);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (75,8881,815074,'1984-03-06 16:01:13','1994-03-06 13:21:14',true,1,8);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (76,9557,934336,'2018-12-24 17:58:32','2028-12-24 15:09:44',false,1,10);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (77,9650,418900,'2000-07-09 20:39:40','2010-07-09 20:01:37',false,1,31);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (78,9862,913607,'2012-04-18 14:15:14','2022-04-18 23:28:06',true,0,35);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (79,6447,228671,'2006-09-26 16:21:35','2016-09-26 0:36:45',true,1,22);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (80,6871,264460,'1990-03-30 16:46:32','2000-03-30 19:21:31',true,0,41);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (81,2091,897409,'1974-03-15 21:04:24','1984-03-15 15:16:48',false,0,12);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (82,7101,383680,'2021-09-10 21:35:03','2031-09-10 21:01:02',true,1,4);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (83,6715,820870,'1998-01-29 20:20:57','2008-01-29 14:00:45',false,1,34);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (84,9174,362100,'2003-02-06 22:11:14','2013-02-06 17:27:28',false,0,17);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (85,1570,404126,'1974-01-11 13:36:32','1984-01-11 20:08:42',true,0,30);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (86,2212,724358,'1992-09-21 16:10:30','2002-09-21 13:06:14',false,1,31);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (87,4177,455167,'1975-08-23 20:25:26','1985-08-23 18:18:57',false,0,44);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (88,2753,909752,'1993-02-01 18:18:21','2003-02-01 13:52:49',false,0,28);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (89,4103,664419,'1999-07-08 18:56:53','2009-07-08 0:39:04',false,0,16);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (90,9539,256061,'2000-12-10 18:30:21','2010-12-10 20:28:18',true,0,40);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (91,4189,385337,'2021-06-08 20:28:27','2031-06-08 22:42:26',false,0,16);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (92,4728,986042,'1990-11-06 21:11:13','2000-11-06 17:30:29',false,1,23);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (93,2884,823332,'2019-12-13 16:38:13','2029-12-13 1:08:46',true,0,1);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (94,2107,563342,'2009-07-29 0:08:02','2019-07-29 12:34:23',true,0,26);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (95,6385,168840,'2016-04-09 18:54:23','2026-04-09 15:07:45',false,0,21);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (96,1979,924318,'2001-08-17 19:41:47','2011-08-17 19:40:25',true,1,42);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (97,1794,861108,'1985-01-23 12:50:39','1995-01-23 22:18:22',true,1,46);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (98,3849,407013,'2019-12-15 13:22:27','2029-12-15 14:10:16',true,0,30);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (99,3524,849279,'2012-10-09 16:01:39','2022-10-09 16:16:03',true,1,16);
INSERT INTO public.passport (id, serial_number, number, issue_date, expiration_date, active, passport_type, person_id) VALUES (100,8218,509895,'1990-12-26 18:49:39','2000-12-26 21:40:50',false,0,16);
