CREATE TABLE passport (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  serial_number INTEGER,
  number INTEGER NOT NULL,
  issue_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  expiration_date date NOT NULL,
  active BOOLEAN NOT NULL,
  passport_type INTEGER NOT NULL,
  person_id BIGINT,
  CONSTRAINT pk_passport PRIMARY KEY (id)
);

ALTER TABLE passport ADD CONSTRAINT uc_passport_number UNIQUE (number);